new APIs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,24 +2,35 @@ name: Deploy APIs
 
 on:
   workflow_dispatch:
+  push:
+    branches: [ main ]
+    paths:
+      - 'api-*.json'
+      - 'oas-*.json'
+      - 'policy-*.json'
+      - '.tyk.json'
 
 jobs:
   deploy:
-    env:
-      dashboard_url: ${{ secrets.DASHBOARD_URL }}
-      dash_key: ${{ secrets.DASH_KEY }}
     runs-on: ubuntu-latest
     name: Deploy Tyk APIs
+    
+    env:
+      DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
+      DASH_KEY: ${{ secrets.DASH_KEY }}
+
     steps:
-     - run: echo "starting sync"
-     - run: echo "${{ runner.os }} operating system"
-     - run: echo "$dashboard_url"
-     - name: Check Out
-       uses: actions/checkout@v4
-     - run: ls -a
-     - run: |
-         curl -s https://packagecloud.io/install/repositories/tyk/tyk-sync/script.deb.sh | sudo bash
-     - run: |
-         sudo apt-get install tyk-sync=1.5.0
-     - run: |
-         /opt/tyk-sync/tyk-sync sync -d="$dashboard_url" -s="$dash_key" -p="."
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install Tyk Sync
+        run: |
+          curl -s https://packagecloud.io/install/repositories/tyk/tyk-sync/script.deb.sh | sudo bash
+          sudo apt-get install tyk-sync=2.0.0
+        
+      - name: Sync APIs
+        run: |
+          if ! /opt/tyk-sync/tyk-sync sync -d="${DASHBOARD_URL}" -s="${DASH_KEY}" -p="."; then
+            echo "Failed to sync APIs"
+            exit 1
+          fi
